[theme]

# Dracula theme

#primaryColor="#bd93f9"
#backgroundColor="#282a36"
#secondaryBackgroundColor="#44475a"
#textColor="#f8f8f2"

# Yellow theme
#primaryColor="#1a191c"
#backgroundColor="#eeeeee"
#secondaryBackgroundColor="#f8d230"
#textColor="#1a191c"

# Spotify theme

primaryColor="#19d860"
backgroundColor="#353535"
secondaryBackgroundColor="#000000"
textColor="#ffffff"

